# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Piotr Wittchen
subtitle: personal website and blog
description: personal website and blog
author: Piotr Wittchen
language: en
timezone: Europe/Warsaw

# address to repo with this project
repo: https://github.com/pwittchen/wittchen.io

# address of the rest api documentation
restapi: https://github.com/pwittchen/wittchen.io#rest-api

# links related to the author
github: /gh 
stackoverflow: /so
twitter: /tw 
linkedin: /in 
email: mailto:piotr@wittchen.io

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://wittchen.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false 
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: custom 

# Deployment
# note: I'm not using this hexo config and making deployment via Makefile and ftpsync
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type:

menu:
    Blog: /
    About: about
    Code: code
    Projects: projects
    Talks: talks
    Archive: archives
    Tags: tags
    Rss: feed.xml
    Contact: contact

alias:
    code/index.html: https://github.com/pwittchen
    gh/index.html: https://github.com/pwittchen
    in/index.html: https://www.linkedin.com/in/piotrwittchen
    so/index.html: https://stackoverflow.com/users/1150795/piotr-wittchen
    tw/index.html: https://twitter.com/piotr_wittchen
    fb/index.html: https://www.facebook.com/piotr.wittchen
    ps/index.html: projects
    ts/index.html: talks

startyear: 2013

feed:
  type: atom
  path: feed.xml
  limit: 20
  content_limit: 140

# rest api configuration
restful:
  site: true
  posts_size: 10
  posts_props:
    title: true
    slug: false
    date: true
    updated: true
    comments: false
    path: true
    excerpt: false
    cover: false
    content: false
    keywords: false
    categories: false
    tags: true
  categories: false
  tags: true
  post: true
  pages: true

# google analytics tracking id
ga: UA-2194664-7
