baseURL = "https://wittchen.io/"
languageCode = "en-us"
title = "Piotr Wittchen"
theme = "book"
enableGitInfo = true
googleAnalytics = "UA-2194664-7"

[taxonomies]
  tags = "tags"

[params]
  BookToc = true
  BookMenuBundle = '/menu'
  BookLogo = 'avatar.png'
  BookRepo = 'https://github.com/pwittchen/wittchen.io'
  BookEditPath = 'edit/master/content'
  BookDateFormat = 'Jan 2, 2006'
  BookSearch = true
