#menu:
#    Blog: /
#    Archive: /archives/
#    GitHub: https://github.com/pwittchen
#    Rss: /atom.xml

# Comment
# e.g disqus: seansun
# disqus:
# duoshuo:

# Analytics
# google-analytics:
# ga: 

# Copyright Infomation
# startyear: 2013
