name: Publish Website
on:
  push:
    branches:
      - master
    paths:
      - 'public/*'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: clean
      uses: heowc/action-hexo@master
      with:
        args: clean
    - name: generate
      uses: heowc/action-hexo@master
      with:
        args: generate
    - name: deploy
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: ${{ secrets.FTP_SERVER }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        REMOTE_DIR: ${{ secrets.FTP_REMOTE_DIR }}
        LOCAL_DIR : "public"
        ARGS: --delete --transfer-all
